name: Android

on:
  pull_request:
    branches: ['**']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

#      - name: Run Unit Tests with Coverage
#        run: ./gradlew testDebugUnitTestCoverage
#
#      - name: Generate JaCoCo Report
#        run: ./gradlew createDebugCoverageReport
#
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v4
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: app/build/reports/coverage/debug/report.xml
#          name: android-coverage
#          fail_ci_if_error: true

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
